/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/header/header.vue')['default']
    IndexList: typeof import('./src/components/index-list/index-list.vue')['default']
    Loading: typeof import('./src/components/base/loading/loading.vue')['default']
    MusicList: typeof import('./src/components/music-list/music-list.vue')['default']
    NoResult: typeof import('./src/components/base/no-result/no-result.vue')['default']
    Player: typeof import('./src/components/player/player.vue')['default']
    Poster: typeof import('./src/components/poster/poster.vue')['default']
    ProgressBar: typeof import('./src/components/player/progress-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/base/scroll/scroll.vue')['default']
    Slider: typeof import('./src/components/base/slider/slider.vue')['default']
    SongList: typeof import('./src/components/base/song-list/song-list.vue')['default']
    Tab: typeof import('./src/components/tab/tab.vue')['default']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
  }
}
